### PR TITLE
Filter out duplicate builds correctly

### LINKED ISSUE #27: Job is triggered twice with this plugin
Hi.
I am trying to use this plugin, but it triggers the job twice.
I found that SCMSourceOwner has duplicated jobs like
**job/name_of_job** and **job/name_of_job/job/name_of_repository/**
Could you fix the duplication? or could you let me know the way to avoid this situation?

### LINKED ISSUE #32: This plugin triggers the build twice
### Version report

Jenkins and plugins versions report:

```
Plugin version - 2.3
Jenkins version - 2.235.1
--


<br class="Apple-interchange-newline">
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
Paste here
```

### Reproduction steps

- Step 1 - Enable pull request review webhook in github (as mentioned below)
image

- Step 2 - Configure build on pull request review - as shown below
image

### Results

Expected result:

it should trigger a build only once when the pr is approved.

Actual result:

its triggering the build twice everytime when the pr is approved.

### LINKED ISSUE #49: Trigger more than one job with single PR comment
### Jenkins and plugins versions report

Hello,
I would like to ask a question if your plugin parses further jobs to run if it finds a match? I have a case where I have two separate jobs which I want to trigger with the same PR comment, but logs show it runs only the first match and does not analyze the rest of them. Is this behavior created by design or this is a bug? I am using Jenkins in ver. 2.332.1, GitHub enterprise server 3.3.7 and GitHub PR Comment Build Version: 78.v2dcf62ba199b.

### What Operating System are you using (both controller, and any agents involved in the problem)?

RHEL 8.5 (Ootpa)

### Reproduction steps

1. Step: Clone job which you can trigger by PR comment (i.e. run forest).
2. Step: Try to trigger those jobs by comment.

### Expected Results

Run n-jobs triggered by the same comment

### Actual Results

Run first match

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by lprimak**
Prevents submission of duplicate jobs by comparing them to the ones already submitted.
Fixes the underlying issues while not preventing multiple jobs per action from running

* please use "ignore whitespace" when reviewing *

fixes #27 
fixes #32
fixes #49  

- [X ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ X] Ensure that the pull request title represents the desired changelog entry
- [X ] Please describe what you did
- [X ] Link to relevant issues in GitHub or Jira
- [X ] Link to relevant pull requests, esp. upstream and downstream changes
- [X ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by lprimak** [comment]
@bluesliverx What do you think?

**Comment by bluesliverx** [comment]
Sorry @lprimak, finally looked at this. This solution looks great! My only concern that the job instances may not be exactly equal depending on how they are constructed/stored. The worst that can happen here is that we get duplicate triggers for the same job, however, and you should be able to tell if that is happening or not pretty quickly I think.

I'll get this merged and released, thanks for contributing again!

**Comment by lprimak** [comment]
Thank you! I have been running with this version for a while and haven't seen any duplicate commits.
They used to happen to me all the time, so it should work for most cases :)

**Comment by bluesliverx** [comment]
This has now been released. Thanks again!

**Pull request merged**
